/// Flutter icons DroneIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DroneIcon
///      fonts:
///       - asset: fonts/DroneIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DroneIcon {
  DroneIcon._();

  static const _kFontFam = 'DroneIcon';
  static const String? _kFontPkg = null;

  static const IconData kindpng_536873 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
